### ISSUE TITLE
DTS Portal - Add object table and fields

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-dts-portal#1]
CREATE NEW OBJECT TABLE - ENVIRONMENTS
many instances to one application

- [ ] app id
- [ ] app name
- [ ] notes 
- [ ] date created
- [ ] date deleted 
- [ ] date modified
- [ ] modified by

**Comment by amenity** [comment]
@SurbhiBakshi @dianamartin - Can you size this please? Also, if it's in Sprint 6 it should go to the _On Deck_ (to do) or _In Progress_ pipelines. Thanks! 🙏

**Comment by SurbhiBakshi** [comment]
@amenity @dianamartin , moved to In Progress and sized it as well, thanks!

**Comment by amenity** [comment]
@dianamartin @SurbhiBakshi - does this need more review? If so, what/who?

**Comment by SurbhiBakshi** [comment]
@amenity , @dianamartin and I reviewed it and it needs some more work.

**Comment by SurbhiBakshi** [comment]
- [ ] Is the Add Environment/ Edit Environment functionality to be used only for Knack Applications? If not, the predetermined options for Environment will need to change.

**Comment by dianamartin** [comment]
@SurbhiBakshi I think primarily yes, but it could be for the devs too..not sure if they've been asked to document it in here or not.

**Comment by SurbhiBakshi** [comment]
https://github.com/cityofaustin/atd-data-tech/wiki/Knack%3A-Document-an-Environment-for-an-Application
