### ISSUE TITLE
Polish email address handling in service request form & script

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-knack-dts-portal#4]
We don't want staff members' email addresses or full names to be displayed in Github. That said, the PMs will often reach out to the requestor as part of triage and it is handy for us to have the email address at hand. 

So let's: 
 - Validate the `austintexas.gov` email address in the Knack form. 
 - Put emails into a `<!-- comment -->` in the top of the description.

**Comment by amenity** [comment]
@johnclary Should I move this to the atd-service-bot repo? It sounded like some of it (validation ?) will happen in Knack. So either leave it here or I can make it two separate issues in the relevant repos.

**Comment by johnclary** [comment]
@amenity it's both, actually. You can leave it here; thanks.

**Comment by johnclary** [comment]
@mddilley this is a good one for you, time permitting. cc @mateoclarke

**Comment by johnclary** [comment]
@mddilley would you schedule some time on Thursday for us to deploy this?
